backend:
  name: git-gateway
  branch: main
media_folder: "img"
public_folder: "img"
collections:
  - name: "gallery_data"
    label: "Galéria Adatok"
    files:
      - label: "Képek és Rajzok"
        name: "gallery"
        file: "data/gallery.json"
        fields:
          - {label: "Kép", name: "image", widget: "image"}
          - {label: "Karakter Név", name: "title", widget: "string"}
          - {label: "Típus", name: "type", widget: "string"}
          - {label: "Kategória", name: "category", widget: "select", options: [{label: "Kész", value: "finished"}, {label: "Sketch", value: "sketch"}]}
